version: "3.4"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "7000:80"
  hub:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.hub
    ports:
      - "7001:7001"
    depends_on:
      - db
  db:
    restart: always
    image: mariadb:10.5
    environment:
      - "MYSQL_ROOT_PASSWORD=mypassword"
      - "MYSQL_DATABASE=snapshot"
  score:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.score
    ports:
      - "7002:7002"
    environment:
      - "PORT=7002"
