FROM node:14-buster

RUN apt-get update && apt-get install -y \
        nginx \
    && rm -rf /var/lib/apt/lists/*
COPY conf/nginx.conf /etc/nginx/sites-enabled/default

# Local package must have dist/ directory (https://stackoverflow.com/q/40528053)
COPY snapshot.js /vendor/snapshot.js
RUN cd /vendor/snapshot.js \
 && yarn \
 && yarn build

WORKDIR /app
COPY snapshot .
COPY conf/web.env .env
RUN yarn \
 && yarn build

CMD ["nginx", "-g", "daemon off;"]
